version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myCloudChallengeProject"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-62fj9gzfaaab"
s3_prefix = "myCloudChallengeProject"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
